spin_manifest_version = "1"
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = ""
name = "scomptest"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "starter"
source = "comppp/target/wasm32-wasi/release/comppp.wasm"
allowed_http_hosts = []
sqlite_databases = ["default"]
[component.trigger]
route = "/s"
[component.build]
workdir = "comppp"
command = "cargo component build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[[component]]
id = "nonstarter"
source = "nonstarter/target/wasm32-wasi/release/nonstarter.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/ns"
[component.build]
workdir = "nonstarter"
command = "cargo component build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
